language: go
go:
  - 1.5.3
  - 1.6
  - tip
matrix:
  allow_failures:
    - go: tip
env:
  - GO15VENDOREXPERIMENT: 1
install:
  - make init
script:
  - make test
  - make vet
branches:
  only:
  - master
  - develop
